language: java
jdk:
  - oraclejdk8

install: true

before_script:
    - chmod +x ./src/libs/integration-test-setup.sh
    - ./src/libs/integration-test-setup.sh > src/test/resources/application.properties
    - cat src/test/resources/application.properties

jobs:
  include:
    - stage: test
      script:
        - mvn clean package
        - set -o pipefail
        - mvn -P travis-ci-test clean cobertura:cobertura-integration-test | grep -v "DEBUG"
        - bash <(curl -s https://codecov.io/bash)
    - stage: performance-test
      script:
        - mvn -P performance-test clean verify
      if: branch = master AND type != pull_request

