language: java
jdk:
  - oraclejdk8

before_script:
  - chmod +x ./src/libs/integration-test-setup.sh
  - ./src/libs/integration-test-setup.sh > src/test/resources/application.properties
  - cat src/test/resources/application.properties

script:
  - mvn clean package
  - set -o pipefail
  - mvn -P travis-ci-test clean cobertura:cobertura-integration-test | grep -v "DEBUG"
  - if [ "$TRAVIS_BRANCH" = "master" ]; then mvn -P performance-test clean verify; fi


after_success:
  - bash <(curl -s https://codecov.io/bash)

